Create C sharp MC2000B example
Thorlabs/Light_Control_and_Manipulation_Examples pull request #4
Opened 2024-09-04 07:38 UTC by ZiyingZhang313

2024-10-09 12:21 UTC, manzelmi-thorlabs approved these changes
Code looks great

2024-10-11 21:16 UTC, TrumanMetz requested changes
Overall, these look really good, a couple things need to be fixed but once they are addressed these will be ready to merge.

2024-10-11 21:16 UTC, TrumanMetz commented on C#/FW102C FW212C/FWxC/Program.cs
Works well, I think there is only one issue though. These use a stepper motor so this needs to be homed first before doing anything else. Because of this, the program errors out if the filter wheel is in any other position other than home before starting. Just add a home command before the moves and this will be good to merge.

2024-10-11 21:16 UTC, TrumanMetz commented on C#/MC2000B/MC2000B_Serial/Program.cs
Overall example is really nice and easy for people to use. I just noticed a couple things that will need to be addressed before this gets put up. The reference out frequency that is meant to be displayed isn't being received correctly so it returns as CMD_NOT_DEFINED Hz. Second, the terminal doesn't close when the chopper is stopped, once these two miner things have been fixed they'll be ready to go up. Last thing, I'm the last person that should be correcting anyone's grammar but in line 157 "finishes" should be "finished". GREAT WORK!

2024-10-12 05:58 UTC, ZiyingZhang313 commented on C#/FW102C FW212C/FWxC/Program.cs
Hi Truman, thank you so much for reviewing the code! May I know the detailed error message you encountered? I tested the example with FW102C many times but couldn't reproduce the error. And I couldn't find the HOME command in the command list. Could you please give more hints about how to fix the bug? Thanks so much!

2024-10-12 06:08 UTC, ZiyingZhang313 commented on C#/MC2000B/MC2000B_Serial/Program.cs
Hi Truman, thanks again for your suggestions! I've added commands to clear buffers while fetching the frequency to avoid errors. 
The `device.Close();` command is to close the terminal (`device` is an instance of `SerialPort` class. Is this what you mean?). The naming is a bit misleading. I've added a comment for this command. 
I've corrected the grammar, thanks for pointing this out.

2024-10-16 12:43 UTC, TrumanMetz approved these changes
Looks great.

2024-10-16 12:43 UTC, merged